# Factored out bits of configuration.
from config.archives import *
from config.bio import *
from config.build import *
from config.categories import *
from config.cdn import *
from config.comments import *
from config.dates import *
from config.deploy import *
from config.drafts import *
from config.footer import *
from config.galleries import *
from config.l10n import *
from config.math import *
from config.nav import *
from config.postprocess import *
from config.redirects import *
from config.robots import *
from config.rssatom import *
from config.search import *
from config.social import *
from config.tags import *
from config.teasers import *
from config.theme import *
